### ISSUE TITLE
Quarto blog not compiling after installing quarto-1.2.329-macos.pkg

### ISSUE THREAD

**Issue by DrTomasAragon** [quarto-dev/quarto-web#593]
I have Mac OS M1 Max

Compiling blog worked fine with quarto-1.2.313-macos.pkg

After updating to quarto-1.2.329-macos.pkg, blog no longer compiled. I got this message at terminal
===
tja@ym29vgj95k blog_dev % quarto render myblog                
[ 1/15] posts/2021-05-22-congrats-ucb-sph-class-of-2021/index.qmd
[ 2/15] posts/2022-12-10-becoming-the-best-at-getting-better/index.qmd
[ 3/15] posts/2023-01-14-my-journey-from-r-to-julia/index.qmd

Starting julia-1.8 kernel...Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 20, in <module>
    from jupyter_core.utils import run_sync
ImportError: cannot import name 'run_sync' from 'jupyter_core.utils' (/Users/tja/.julia/conda/3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py)
tja@ym29vgj95k blog_dev % quarto render myblog
===

Then, I reinstalled quarto-1.2.313-macos.pkg, and everything worked fine again:
===
tja@ym29vgj95k blog_dev % quarto render myblog
[ 1/15] posts/2021-05-22-congrats-ucb-sph-class-of-2021/index.qmd
[ 2/15] posts/2022-12-10-becoming-the-best-at-getting-better/index.qmd
[ 3/15] posts/2023-01-14-my-journey-from-r-to-julia/index.qmd

Starting julia-1.8 kernel...Done

Executing 'index.ipynb'
  Cell 1/11...Done
  Cell 2/11...Done
  Cell 3/11...Done
  Cell 4/11...Done
  Cell 5/11...Done
  Cell 6/11...Done
  Cell 7/11...Done
  Cell 8/11...Done
  Cell 9/11...Done
  Cell 10/11...Done
  Cell 11/11...Done

[ 4/15] posts/2017-10-22-humility-is-the-new-smart/index.qmd
[ 5/15] posts/2018-06-11-the-book-of-why/index.qmd
[ 6/15] posts/2021-05-01-seven-principles-for-building-trust/index.qmd
[ 7/15] posts/2018-06-15-how-emotions-are-made/index.qmd
[ 8/15] posts/2021-02-20-new-cdph-job/index.qmd
[ 9/15] posts/2021-03-13-decision-intelligence01/index.qmd
[10/15] posts/2021-05-15-embodying-cultural-humility/index.qmd
[11/15] posts/2022-08-20-decision-intelligence-books/index.qmd
[12/15] works.qmd
[13/15] subscription.qmd
[14/15] index.qmd
[15/15] about.qmd

Output created: _site/index.html
===

CONCLUSION: There is bug with quarto-1.2.329-macos.pkg

**Comment by jjallaire** [comment]
Thanks for reporting this! There was upstream change to `nbclient` which ended up breaking us. The fix we put in however appears to rely on a very new version of the `jupyter_core` package (from just a couple of months ago). We will make our workaround smarter (and print a more clear error diagnostic if there is a need to update `jupyter_core`). In the meantime, if you update your `jupyter_core` package to `>= 5.1` then things should work w/ the 1.2.329 release.

**Comment by DrTomasAragon** [comment]
I have jupyter core 5.1.5, but still not working with Quarto 1.2.329
release.

====

***@***.*** ~ % python3 -m pip install jupyter-core

Requirement already satisfied: jupyter-core in
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
(5.1.5)

Requirement already satisfied: platformdirs>=2.5 in
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
(from jupyter-core) (2.6.2)

Requirement already satisfied: traitlets>=5.3 in
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
(from jupyter-core) (5.8.1)

***@***.*** ~ % cd
/Users/tja/Library/CloudStorage/OneDrive-CADepartmentofPublicHealth/tja/gh/blog_dev

***@***.*** blog_dev % quarto render myblog

[ 1/15] posts/2021-05-22-congrats-ucb-sph-class-of-2021/index.qmd

[ 2/15] posts/2022-12-10-becoming-the-best-at-getting-better/index.qmd

[ 3/15] posts/2023-01-14-my-journey-from-r-to-julia/index.qmd


Starting julia-1.8 kernel...Traceback (most recent call last):

  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>

    from notebook import notebook_execute, RestartKernel

  File "/Applications/quarto/share/jupyter/notebook.py", line 20, in
<module>

    from jupyter_core.utils import run_sync

ImportError: cannot import name 'run_sync' from 'jupyter_core.utils'
(/Users/tja/.julia/conda/3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py)

***@***.*** blog_dev %





Tomás

----
Tomás Aragón
@DrTomasAragon (twitter)

**Comment by jjallaire** [comment]
I believe that we have the correct fix on our v1.3 pre-release (https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.142) and are planning to back port that to v1.2 today (@dragonstyle let's do that this morning).

**Comment by cscheid** [comment]
```
    from jupyter_core.utils import run_sync

ImportError: cannot import name 'run_sync' from 'jupyter_core.utils'
(/Users/tja/.julia/conda/3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py)
```

```
python3 -m pip install jupyter-core

Requirement already satisfied: jupyter-core in
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
(5.1.5)
```

Note that you have multiple conflicting installed versions. jupyter_core 5.1.5 includes run_sync, so the import from your conda environment is using the old version of jupyter_core.

**Comment by DrTomasAragon** [comment]
Thanks! That worked.

I removed '/Users/tja/.julia/conda' and now 1.2.329 run fine.

Tomás

----
Tomás Aragón
@DrTomasAragon (twitter)
